//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Enrollment = new HashSet<Enrollment>();
        }
        
        public int StudentID { get; set; }
        [Required(ErrorMessage = "El campo LastName es obligatorio")]
        public string LastName { get; set; }
        [Required(ErrorMessage = "El campo FirstName es obligatorio")]
        public string FirstName { get; set; }
        [Required(ErrorMessage = "Utilizar @ obligatoriamente")]
        public string Email { get; set; }
        public Nullable<System.DateTime> EnrollmentDate { get; set; }
        [Required(ErrorMessage = "Solo femenino o masculino ")]
        public string Sexo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enrollment> Enrollment { get; set; }
    }
}
